language: haskell

notifications:
  irc: "irc.freenode.org#haskell-game"

before_install:
  sudo apt-get update
  sudo apt-get install libxxf86vm-dev

install:
  cabal install --only-dependencies --enable-tests --force-reinstalls

script:
  cabal configure --enable-tests -fexamples && cabal build && cabal test
